
-- The Brick aggregate
CREATE TABLE BRICK
(
  ID   BIGINT IDENTITY PRIMARY KEY ,
  DESCRIPTION VARCHAR(200)
);

-- The LegoModel aggregate
CREATE TABLE LEGO_MODEL
(
  ID   BIGINT IDENTITY PRIMARY KEY ,
  NAME VARCHAR(200)
);

CREATE TABLE MANUAL
(
  LANGUAGE VARCHAR(10),
  CONTENT VARCHAR(2000),
  LEGO_MODEL BIGINT,
  LEGO_MODEL_KEY SMALLINT,
  PRIMARY KEY (LEGO_MODEL, LEGO_MODEL_KEY),
  FOREIGN KEY (LEGO_MODEL) REFERENCES LEGO_MODEL (ID)
);

CREATE TABLE CONTENT
(
    LEGO_MODEL BIGINT,
    BRICK_ID BIGINT,
    AMOUNT BIGINT,
    PRIMARY KEY (LEGO_MODEL, BRICK_ID),
    FOREIGN KEY (LEGO_MODEL) REFERENCES LEGO_MODEL (ID)
);
